In [1]:
import numpy as np
import pandas as pd

In [8]:
arr=np.array(list(map(int,input().strip().split())))

804 627 794 846 820 705 854 89 355 536 229 195 611 149 912 52 322 523 17 61 933 211 153 651 248 289 95 418 273 416 832 983 794 372 976 813 514 254 169 426 439 197 951 327 798 508 607 252 382 138


In [13]:
arr=arr.reshape(10,5)
print(arr)
print(arr.shape)

[[804 627 794 846 820]
 [705 854  89 355 536]
 [229 195 611 149 912]
 [ 52 322 523  17  61]
 [933 211 153 651 248]
 [289  95 418 273 416]
 [832 983 794 372 976]
 [813 514 254 169 426]
 [439 197 951 327 798]
 [508 607 252 382 138]]
(10, 5)


In [14]:
example = np.array([[1,2,3,4,5], [6,7,8,9,10],[12,13,15,17,18]]) 
example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 15, 17, 18]])

In [17]:
print(example[2,3])

17


In [27]:
#creating 1-D array to 3-D array
arr1=np.array(list(map(int,input().strip().split())),ndmin=5)

9 4 8 16 17 11 


In [28]:
arr1

array([[[[[ 9,  4,  8, 16, 17, 11]]]]])

In [35]:
n=int(input('Enter how many rows required: '))
arr2=np.array([list(map(int,input().split())) for i in range(n)])

Enter how many rows required: 4
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16


In [37]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr2[0:2,0:4:2]

array([[1, 3],
       [5, 7]])

In [ ]:
#numpy broadcasting

In [39]:
n=int(input('Enter number of rows'))
arr=np.array([list(map(int,input().strip().split())) for i in range(n)])

Enter number of rows4
1 2 3 4 
5 6 7 8 
9 10 11 12
13 14 15 16


In [41]:
arr+1-2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
n=int(input())
arr=np.array([list(map(int,input().split())) for i in range(n)])

2
1 2
3 4


In [43]:
arr

array([[1, 2],
       [3, 4]])

In [51]:
arr=arr.flatten()
arr

array([1, 2, 3, 4])

In [50]:
arr.shape

(4,)

In [ ]:
#Numpy search where

In [73]:
arr=list(map(int,input().strip().split()))
arr=np.array(arr)

2 1 2 3 4 5 8 7 8


In [74]:
arr=np.where(arr==8)

In [75]:
arr

(array([6, 8], dtype=int64),)

In [ ]:
#Numpy search string locations

In [81]:
# n=int(input('enter input for first arr:'))
x=(np.array((input().split())))
y=(np.where(x=="Apple"))[0]
print("Apple occures {} times in the list at {} location".format(len(y),y))

 Apple Banana Apple Apple Banana
Apple occures 3 times in the list at [0 2 3] location


In [ ]:
#Nisha is having list of the people's height in inches. 
#She wants to convert height into centimeters. 
#Help her to complete her task by writing a python code using NumPy library.

In [3]:
arr=np.array(list(map(int,input().strip().split())))
arr_new=arr*2.54


48 49 50


In [4]:
arr_new.round(2)

array([121.92, 124.46, 127.  ])

In [ ]:
#You are given two space-separated numbers in the input for forming a range. 
#The first number is odd. 
#Your task is to create a NumPy array of the even numbers in the given range.

In [22]:
m,n=map(int,(input().split()))
x=np.arange(m+1,n,2)
print(x)

1 12
[ 2  4  6  8 10]


In [ ]:
#You are given two space-separated integers in the input. 
#Your task is to create a NumPy array by dividing the range into n number of eqaul elements. 
#Also, print the shape of the array.

In [30]:
a,b=map(int,(input().split())))

1 10


In [27]:
c=int(input('number of elements of range'))

number of elements of range5


In [28]:
c

5

In [34]:
d=np.linspace(a,b,c)
print(d)
print(d.shape)

[ 1.    3.25  5.5   7.75 10.  ]
(5,)


In [ ]:
#You are given three lines of input. Each line has three space-separated integers. 
#Your task is to create a NumPy array as follows. 
#1) 1 D array of the shape (3,) from the first line of the input

#2) 2 D array of the shape (2,3) from the first line and second line of the input

#3) 2 D array of the shape (3,3) from all lines of the inputs

#print arrays and their shapes one after another.

In [35]:
n=int(input('enter number of lines of output:'))
x=np.array([list(map(int,input().strip().split())) for i in range(n)])

enter number of lines of output:3
1 2 3
4 5 6
7 8 9


In [36]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a=x[0,:]
print(a)
print(a.shape)
b=x[0:2,:]
print(b)
print(b.shape)
c=x[0:3,:]
print(c)
print(c.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
#You are given an integer n. Your task is to create:

#1) a NumPy array of zeros as a float of the shape n

#2) a NumPy array of zeros as int of the shape nxn

#3) a NumPy array of ones as int of the shape n

#4) a NumPy array of ones as a float of the shape nxn

In [42]:
n=int(input())

3


In [62]:
a=np.zeros(n)
b=np.zeros((n,n),dtype=int)
c=np.ones(n,dtype=int)
d=np.ones((n,n))

In [63]:
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)
print(b)
print(b.size)
print(b.ndim)
print(b.dtype)
print(c)
print(c.size)
print(c.ndim)
print(c.dtype)
print(d)
print(d.size)
print(d.ndim)
print(d.dtype)

[0. 0. 0.]
3
1
float64
[[0 0 0]
 [0 0 0]
 [0 0 0]]
9
2
int32
[1 1 1]
3
1
int32
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
9
2
float64


In [ ]:
#You are given an input of space-separated six integers. 
#Your task is to create a 1D NumPy array and slice the array like

#1) first two elements as an NumPy array

#2) elements form the first index till the fourth index as an NumPy array

#3) last two elements as an NumPy array

#The print shape of each array includes the original array.

In [87]:
a=np.array(list(map(int,input().split())))

1 2 3 4 5 6


In [88]:
a

array([1, 2, 3, 4, 5, 6])

In [92]:
print(a[0:2])
print(a[0:2].shape)
print(a[1:5])
print(a[1:5].shape)
print(a[-2:])
print(a[-2:].shape)

[1 2]
(2,)
[2 3 4 5]
(4,)
[5 6]
(2,)


In [ ]:
#You are given a line of input that contains six space-separated integers. Your task is to create

#1) 1D NumPy array, arr1.

#2) reshape that array with shape (2,3) as arr2.

#3) reshape the arr1 array with shape (2,3,1) as arr3.

#4) reshape arr3 array as a 1D array as arr4.

#print shapes and dimensions of each array.

In [93]:
a=(np.array(list(map(int,input().split()))))

1 2 3 4 5 6


In [95]:
print(a)

[1 2 3 4 5 6]


In [107]:
arr1=a
arr2=a.reshape(2,3)
arr3=a.reshape(2,3,1)
arr4=arr3.flatten()

In [113]:
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr4)
print(arr4.shape)
print(arr4.ndim)

[1 2 3 4 5 6]
(6,)
1
[[1 2 3]
 [4 5 6]]
(2, 3)
2
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)
3
[1 2 3 4 5 6]
(6,)
1


In [ ]:
#You are given n lines of input and each line contains n space-separated integers. 
#Your task is to create a NumPy array of size nxn and grab the element present at (nth row, nth column) position

In [120]:
import numpy as np 
n=int(input())
arr=np.array([list(map(int,input().split())) for i in range(n)])
print(arr)
print(arr[n-1,n-1])

2
1 2
3 4
[[1 2]
 [3 4]]
4


In [ ]:
#There is n number of workers are working on a construction site. 
#Each of them is having different hourly rate in rupees and also they work for a different number of hours in a day. 
#While moving out from the site they get their salary in hand. 
#Your task is to create a numpy array which contains names and their daily wages

In [127]:
names=list(input().split())
rate=np.array(list(map(float,input().split())))
hours=np.array(list(map(int,input().split())))

John Johnny Janardhan
250.5 160.5 200.0
5 6 8


In [128]:
wage=rate*hours
print(np.array([names,wage]))

[['John' 'Johnny' 'Janardhan']
 ['1252.5' '963.0' '1600.0']]


In [ ]:
#You are given two 2D NumPy arrays. Concatenate them column-wise and row-wise.

In [130]:
n=int(input())
x=np.array([list(map(int,input().split())) for i in range(n)])
m=int(input())
y=np.array([list(map(int,input().split())) for i in range(m)])

2
1 2 3
4 5 6
2
6 7 8
9 10 11


In [132]:
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 6  7  8]
 [ 9 10 11]]


In [138]:
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [139]:
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#You are given m number of space-separated integers for a 1D Numpy array. 
#Your task is to find out the index of the numbers in the NumPy array given in the list.

In [143]:
z=np.array(list(map(int,input().split())))
x=list(map(int,input().split()))
for i in x:
    print(np.where(z==i))

1 2 3 4 5 6
2 5
(array([1], dtype=int64),)
(array([4], dtype=int64),)


In [147]:
a=np.array([1,2,3,4,5,6])
np.where(a==1)

(array([0], dtype=int64),)

In [ ]:
#You are given a Numpy array which contains the heights of the people in the inches. 
#Your task is to convert the values into centimeters and then sort them in ascending order.

In [152]:
heights=np.array(list(map(int,input().split())))

55 60 54 53 62 58 59


In [153]:
height_in_cm=heights*2.54

In [154]:
np.sort(height_in_cm)

array([134.62, 137.16, 139.7 , 147.32, 149.86, 152.4 , 157.48])

In [ ]:
#Roots of a polynomial equation

In [157]:
print(np.roots([4,-3,-25,-6]))
print(np.round(np.roots([1,-4,-7,14,-44,120])))

[ 3.   -2.   -0.25]
[ 5.+0.j -3.+0.j -0.+2.j -0.-2.j  2.+0.j]


In [ ]:
#leading and trailing space removal numpy
#[' python exercises ', '    Pandas     ', '    Numpy    ', '      Board Infinity']

In [166]:
list1=np.array([' python exercises ', '    Pandas     ', '    Numpy    ', '      Board Infinity'])
np.char.strip(list1)


array(['python exercises', 'Pandas', 'Numpy', 'Board Infinity'],
      dtype='<U20')

In [ ]:
#Numpy array slicing

In [167]:
import numpy as np 
example = np.array([[1,2,3,4,5], [6,7,8,9,10],[12,13,15,17,18]]) 
example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 15, 17, 18]])

In [170]:
example[2,3]

17

In [ ]:
#changing data type of an array
#You are given 1D numpy array. Change the array of floats to an array of integers and print the new array and it's datatype.

#All column data is of object datatype.Change it to appropriate datatype and then apply logic

#All column data is of object datatype.Change it to appropriate datatype and then apply logic

#All column data is of object datatype.Change it to appropriate datatype and then apply logic

In [174]:
arr = np.array([1.3, 2.2, 3.1]) 
arr

array([1.3, 2.2, 3.1])

In [184]:
arr=arr.astype('i')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [ ]:
#Use of copy function in numpy

In [191]:
import numpy as np 
arr = np.array([25,60,8,7]) 
a=arr.copy() #copying an array
a[1]=2
print(a)

[25  2  8  7]


In [ ]:
#Find repetitive element in numpy arrar

In [193]:
import numpy as np
def array(arr):
    arr1=np.array(arr,dtype=int) 
    save=[]
    sorts=sorted(arr1)
    for i in range(len(arr1)):
        if sorts[i-1]==sorts[i]:
            save.append(sorts[i])
    return save
arr=input().strip().split()
print(array(arr))

1 2 3 2 1 2 4 5 6
[1, 2, 2]


In [194]:
#create padding in numpy array

In [195]:
import numpy as np
def array(arr1,arr2,arr3):
    arr1=np.array(arr1,dtype=int)
    arr2=np.array(arr2,dtype=int)
    arr3=np.array(arr3,dtype=int)
#Write your code here
    arr=np.array([arr1,arr1,arr2])
    return np.pad(arr,pad_width=3,mode='constant',constant_values=1)
arr1=input().strip().split()
arr2=input().strip().split()
arr3=input().strip().split()

print(array(arr1,arr2,arr3))

804 627 794
705 854 89
229 195 611
[[  1   1   1   1   1   1   1   1   1]
 [  1   1   1   1   1   1   1   1   1]
 [  1   1   1   1   1   1   1   1   1]
 [  1   1   1 804 627 794   1   1   1]
 [  1   1   1 804 627 794   1   1   1]
 [  1   1   1 705 854  89   1   1   1]
 [  1   1   1   1   1   1   1   1   1]
 [  1   1   1   1   1   1   1   1   1]
 [  1   1   1   1   1   1   1   1   1]]


In [ ]:
#numpy unique values and frequency of the unique numbers
#You are given a space separated array of numbers. 
#Write a numpy program to get all the unique elements in that array and also return the frequency of that unique numbers.

In [196]:
import numpy as np
def array(arr):
    arr=np.array(arr,dtype=int)
    
    unique, frequency = np.unique(arr,return_counts = True)
    
    return unique,frequency

arr=input().strip().split()

print(array(arr))

1 2 3 5 4 8 9 2 5 7 9 2 9
(array([1, 2, 3, 4, 5, 7, 8, 9]), array([1, 3, 1, 1, 2, 1, 1, 3], dtype=int64))
